sudo: required

language: node_js
node_js:
  - "5.8"

services:
  - docker

# testing is built in to the docker images
script:
  - make pull # pull the images first to give us something cached to build off of
  - make all